// <auto-generated />
using System;
using API_Labb3.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_Labb3.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240428054934_Initial creation")]
    partial class Initialcreation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API_Labb3.Models.Interest", b =>
                {
                    b.Property<int>("InterestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InterestId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InterestId");

                    b.ToTable("Interests");

                    b.HasData(
                        new
                        {
                            InterestId = 1,
                            Description = "Protecting systems and data from digital attacks",
                            Title = "Cybersecurity"
                        },
                        new
                        {
                            InterestId = 2,
                            Description = "Extracting knowledge and insights from structured and unstructured data",
                            Title = "Data Science"
                        },
                        new
                        {
                            InterestId = 3,
                            Description = "Creating intelligent machines that react and work like humans",
                            Title = "Artificial Intelligence"
                        },
                        new
                        {
                            InterestId = 4,
                            Description = "Building and maintaining websites or web applications",
                            Title = "Web Development"
                        });
                });

            modelBuilder.Entity("API_Labb3.Models.Link", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("InterestId")
                        .HasColumnType("int");

                    b.Property<int?>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InterestId");

                    b.HasIndex("PersonId");

                    b.ToTable("Links");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InterestId = 2,
                            PersonId = 1,
                            Url = "https://www.datasciencecentral.com/"
                        },
                        new
                        {
                            Id = 2,
                            InterestId = 2,
                            PersonId = 2,
                            Url = "https://www.datasciencecentral.com/"
                        },
                        new
                        {
                            Id = 3,
                            InterestId = 1,
                            PersonId = 3,
                            Url = "https://www.datasciencecentral.com/"
                        },
                        new
                        {
                            Id = 4,
                            InterestId = 4,
                            PersonId = 2,
                            Url = "https://www.datasciencecentral.com/"
                        });
                });

            modelBuilder.Entity("API_Labb3.Models.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonId"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonId");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            PersonId = 1,
                            Name = "Sanna Harrysson",
                            PhoneNumber = "123456456"
                        },
                        new
                        {
                            PersonId = 2,
                            Name = "Kalah Berggren",
                            PhoneNumber = "5546654"
                        },
                        new
                        {
                            PersonId = 3,
                            Name = "Göran Bengtsson",
                            PhoneNumber = "5645221"
                        });
                });

            modelBuilder.Entity("InterestPerson", b =>
                {
                    b.Property<int>("InterestsInterestId")
                        .HasColumnType("int");

                    b.Property<int>("PersonsPersonId")
                        .HasColumnType("int");

                    b.HasKey("InterestsInterestId", "PersonsPersonId");

                    b.HasIndex("PersonsPersonId");

                    b.ToTable("InterestPerson");
                });

            modelBuilder.Entity("API_Labb3.Models.Link", b =>
                {
                    b.HasOne("API_Labb3.Models.Interest", "Interest")
                        .WithMany("Links")
                        .HasForeignKey("InterestId");

                    b.HasOne("API_Labb3.Models.Person", "Person")
                        .WithMany("Links")
                        .HasForeignKey("PersonId");

                    b.Navigation("Interest");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("InterestPerson", b =>
                {
                    b.HasOne("API_Labb3.Models.Interest", null)
                        .WithMany()
                        .HasForeignKey("InterestsInterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_Labb3.Models.Person", null)
                        .WithMany()
                        .HasForeignKey("PersonsPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("API_Labb3.Models.Interest", b =>
                {
                    b.Navigation("Links");
                });

            modelBuilder.Entity("API_Labb3.Models.Person", b =>
                {
                    b.Navigation("Links");
                });
#pragma warning restore 612, 618
        }
    }
}
